### ISSUE TITLE
Error: missing return true statement for connectToServer function for BLE_Client_OLED (Module 5 Unit 4 ESP32 Course)

### ISSUE THREAD

**Issue by mightylastingcode** [RuiSantosdotme/ESP32-Course#1]
bool connectToServer(BLEAddress pAddress) {
...
   return false;
...
 return true;  // missing return true statement.  Added by me. !!!
}

**Comment by RuiSantosdotme** [comment]
Thanks! I've added the return true: https://github.com/RuiSantosdotme/ESP32-Course/blob/master/code/BLE_Client_OLED/BLE_Client_OLED.ino
